### PR TITLE
React Navbar Component Added For HacktoberFest

### PR DESCRIPTION
**Pull request by deven-533**
Ma'am, I have Sent My Pull Request Regarding Issue #1, Please Merge my Pull Request for The Navbar Template Using ReactJS
and Ma'am Kindly Please Add hacktoberfest-accepted or hacktoberfest tag to my Pull Request while merging it with the main branch

Here is the View of the Navbar Component (It Also Has Hover Effects)
image

### CODE REVIEW

**Comment by GauriKashyap** [comment]
Good work, instead of the word "website-header" can you right portfolio website?

**Comment by deven-533** [comment]
> Good work, instead of the word "website-header" can you right portfolio website?

Okay Ma'am I will Delete this PR and will send You updated PR

**Comment by deven-533** [comment]
> Good work, instead of the word "website-header" can you right portfolio website?

Ok Ma'am I will Reflect the changes you have suggested to me very soon

**Comment by deven-533** [comment]
Ma'am I Have Modified the Pull Request as per the requirements, Kindly, Please Merge it for Issue #1 and Add hacktoberfest and hacktoberfest-accepted tag to my pull request

You Can Check The Preview of the Navbar Component as Follows :
image

**Comment by GauriKashyap** [comment]
Can you make the font a bit different? like something which looks more decent?

**Comment by deven-533** [comment]
> Can you make the font a bit different? like something which looks more decent?

Okay Ma'am Working on it

**Comment by deven-533** [comment]
Ma'am modified the PR for the decent font. Kindly, Please Merge it for Issue #1 and Add hacktoberfest and hacktoberfest-accepted tag to my pull request.

You Can Check The Preview of the Navbar Component as Follows :
image

**Comment by deven-533** [comment]
Ma'am any problem with the Pull Request??

**Pull request merged**
